---
title       : My Home Loan EMI Calculator App
subtitle    : 
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- .class #2 

## EMI Calculator for Home Loan







### -This tool  can calculate a monthly EMI amount for a home loan

### -This tool  produces a full repayment(Amortization) schedule for home loan

### -This tool  prodcuces a plot of repayment pattern

### -This tool  is a useful tool to estimate the cost of loan based on applicable interest

### -This tool is available free of cost

--- .class #3
## What is EMI?

Equated Monthly Installment - EMI for short - is the amount payable every month to the bank until the loan amount is fully paid off.It consists of the interest on loan as well as part of the principal amount to be repaid. This amount has to be paid monthly. The interest component of the EMI would be larger during the initial months and gradually reduce with each payment.Even though your monthly EMI payment won't change, the proportion of principal and interest components will change with time. With each successive payment, you'll pay more towards the principal and less in interest.
##### The formula to calculate EMI is :
EMI = [P x R x (1+R)N]/[(1+R)N-1], where P stands for the loan amount or principal, R is the interest rate per month and N is the number of monthly instalments. 

##### Lets Take an example :
if you borrow amount 10,00,000 from the bank at 10.5% annual interest for a period of 10 years (i.e., 120 months), then EMI = 10,00,000 * 0.00875 * (1 + 0.00875)120 / ((1 + 0.00875)120 - 1) = 13,493. i.e., you will have to pay 13,493 for 120 months to repay the entire loan amount. The total amount payable will be 13,493 * 120 = 16,19,220 that includes 6,19,220 as interest toward the loan.


--- .class #4
## How to use EMI calculator?

With 3 useful tabs and instant results, this Home loan EMI calculator is easy to use, intuitive to understand and is quick to perform. 

You can calculate EMI for home loan fully amortizing loan using this tool.

Use Slider bars to change following information in the EMI calculator:
Principal loan amount you wish to avail
Loan term (years)
Rate of interest (yearly percentage)

Use the slider to adjust the values in the EMI calculator form. 
I have tried to keep highest precision values in these slider. 

As soon as the values are changed using the slider , Home loan EMI calculator will re-calculate your monthly payment (EMI) amount,Amortization schedule and installment pattern.

--- .class #5

## References 

### -http://www.emicalculator.net/


### -http://businesstoday.intoday.in/story/how-to-calculate-emi-on-your-loans-formula-explanation/1/198944.html


### -http://shiny.rstudio.com/tutorial/lesson3/


### -http://rmarkdown.rstudio.com/authoring_basics.html


